(function () {

var $dropDataPlugin = function () {};

$dropDataPlugin.drop = {};
//font drops
$dropDataPlugin.drop.fonts = [];
$dropDataPlugin.drop.fonts.push({text:"Aharoni",value:"Aharoni"});
$dropDataPlugin.drop.fonts.push({text:"Andalus",value:"Andalus"});
$dropDataPlugin.drop.fonts.push({text:"AngsanaNew",value:"AngsanaNew"});
$dropDataPlugin.drop.fonts.push({text:"AngsanaUPC",value:"AngsanaUPC"});
$dropDataPlugin.drop.fonts.push({text:"Aparajita",value:"Aparajita"});
$dropDataPlugin.drop.fonts.push({text:"ArabicTypesetting",value:"ArabicTypesetting"});
$dropDataPlugin.drop.fonts.push({text:"Arial",value:"Arial"});
$dropDataPlugin.drop.fonts.push({text:"ArialBlack",value:"ArialBlack"});
$dropDataPlugin.drop.fonts.push({text:"Batang",value:"Batang"});
$dropDataPlugin.drop.fonts.push({text:"BatangChe",value:"BatangChe"});
$dropDataPlugin.drop.fonts.push({text:"BrowalliaNew",value:"BrowalliaNew"});
$dropDataPlugin.drop.fonts.push({text:"BrowalliaUPC",value:"BrowalliaUPC"});
$dropDataPlugin.drop.fonts.push({text:"Calibri",value:"Calibri"});
$dropDataPlugin.drop.fonts.push({text:"Cambria",value:"Cambria"});
$dropDataPlugin.drop.fonts.push({text:"CambriaMath",value:"CambriaMath"});
$dropDataPlugin.drop.fonts.push({text:"Candara;",value:"Candara;"});
$dropDataPlugin.drop.fonts.push({text:"ComicSansMS",value:"ComicSansMS"});
$dropDataPlugin.drop.fonts.push({text:"Consolas",value:"Consolas"});
$dropDataPlugin.drop.fonts.push({text:"Constantia",value:"Constantia"});
$dropDataPlugin.drop.fonts.push({text:"Corbel",value:"Corbel"});
$dropDataPlugin.drop.fonts.push({text:"CordiaNew",value:"CordiaNew"});
$dropDataPlugin.drop.fonts.push({text:"CordiaUPC",value:"CordiaUPC"});
$dropDataPlugin.drop.fonts.push({text:"CourierNew",value:"CourierNew"});
$dropDataPlugin.drop.fonts.push({text:"DaunPenh",value:"DaunPenh"});
$dropDataPlugin.drop.fonts.push({text:"David",value:"David"});
$dropDataPlugin.drop.fonts.push({text:"DFKai-SB",value:"DFKai-SB"});
$dropDataPlugin.drop.fonts.push({text:"DilleniaUPC",value:"DilleniaUPC"});
$dropDataPlugin.drop.fonts.push({text:"DokChampa",value:"DokChampa"});
$dropDataPlugin.drop.fonts.push({text:"Dotum",value:"Dotum"});
$dropDataPlugin.drop.fonts.push({text:"DotumChe",value:"DotumChe"});
$dropDataPlugin.drop.fonts.push({text:"Ebrima",value:"Ebrima"});
$dropDataPlugin.drop.fonts.push({text:"EstrangeloEdessa",value:"EstrangeloEdessa"});
$dropDataPlugin.drop.fonts.push({text:"EucrosiaUPC",value:"EucrosiaUPC"});
$dropDataPlugin.drop.fonts.push({text:"Euphemia",value:"Euphemia"});
$dropDataPlugin.drop.fonts.push({text:"FangSong",value:"FangSong"});
$dropDataPlugin.drop.fonts.push({text:"FranklinGothicMedium",value:"FranklinGothicMedium"});
$dropDataPlugin.drop.fonts.push({text:"FrankRuehl",value:"FrankRuehl"});
$dropDataPlugin.drop.fonts.push({text:"FreesiaUPC",value:"FreesiaUPC"});
$dropDataPlugin.drop.fonts.push({text:"Gabriola",value:"Gabriola"});
$dropDataPlugin.drop.fonts.push({text:"Gautami",value:"Gautami"});
$dropDataPlugin.drop.fonts.push({text:"Georgia",value:"Georgia"});
$dropDataPlugin.drop.fonts.push({text:"Gisha",value:"Gisha"});
$dropDataPlugin.drop.fonts.push({text:"Gulim",value:"Gulim"});
$dropDataPlugin.drop.fonts.push({text:"GulimChe",value:"GulimChe"});
$dropDataPlugin.drop.fonts.push({text:"Gungsuh",value:"Gungsuh"});
$dropDataPlugin.drop.fonts.push({text:"GungsuhChe",value:"GungsuhChe"});
$dropDataPlugin.drop.fonts.push({text:"Impact",value:"Impact"});
$dropDataPlugin.drop.fonts.push({text:"IrisUPC",value:"IrisUPC"});
$dropDataPlugin.drop.fonts.push({text:"IskoolaPota",value:"IskoolaPota"});
$dropDataPlugin.drop.fonts.push({text:"JasmineUPC",value:"JasmineUPC"});
$dropDataPlugin.drop.fonts.push({text:"KaiTi",value:"KaiTi"});
$dropDataPlugin.drop.fonts.push({text:"Kalinga",value:"Kalinga"});
$dropDataPlugin.drop.fonts.push({text:"Kartika",value:"Kartika"});
$dropDataPlugin.drop.fonts.push({text:"KhmerUI",value:"KhmerUI"});
$dropDataPlugin.drop.fonts.push({text:"KodchiangUPC",value:"KodchiangUPC"});
$dropDataPlugin.drop.fonts.push({text:"Kokila",value:"Kokila"});
$dropDataPlugin.drop.fonts.push({text:"LaoUI",value:"LaoUI"});
$dropDataPlugin.drop.fonts.push({text:"Latha",value:"Latha"});
$dropDataPlugin.drop.fonts.push({text:"Leelawadee",value:"Leelawadee"});
$dropDataPlugin.drop.fonts.push({text:"LevenimMT",value:"LevenimMT"});
$dropDataPlugin.drop.fonts.push({text:"LilyUPC",value:"LilyUPC"});
$dropDataPlugin.drop.fonts.push({text:"LucidaConsole",value:"LucidaConsole"});
$dropDataPlugin.drop.fonts.push({text:"LucidaSansUnicode",value:"LucidaSansUnicode"});
$dropDataPlugin.drop.fonts.push({text:"MalgunGothic",value:"MalgunGothic"});
$dropDataPlugin.drop.fonts.push({text:"Mangal",value:"Mangal"});
$dropDataPlugin.drop.fonts.push({text:"Marlett",value:"Marlett"});
$dropDataPlugin.drop.fonts.push({text:"Meiryo",value:"Meiryo"});
$dropDataPlugin.drop.fonts.push({text:"MeiryoUI",value:"MeiryoUI"});
$dropDataPlugin.drop.fonts.push({text:"MicrosoftHimalaya",value:"MicrosoftHimalaya"});
$dropDataPlugin.drop.fonts.push({text:"MicrosoftJhengHei",value:"MicrosoftJhengHei"});
$dropDataPlugin.drop.fonts.push({text:"MicrosoftNewTaiLue",value:"MicrosoftNewTaiLue"});
$dropDataPlugin.drop.fonts.push({text:"MicrosoftPhagsPa",value:"MicrosoftPhagsPa"});
$dropDataPlugin.drop.fonts.push({text:"MicrosoftSansSerif",value:"MicrosoftSansSerif"});
$dropDataPlugin.drop.fonts.push({text:"MicrosoftTaiLe",value:"MicrosoftTaiLe"});
$dropDataPlugin.drop.fonts.push({text:"MicrosoftUighur",value:"MicrosoftUighur"});

//font margin
$dropDataPlugin.drop.margin = [];
$dropDataPlugin.drop.margin.push({text:"0",value:"0"});
$dropDataPlugin.drop.margin.push({text:"1",value:"1"});
$dropDataPlugin.drop.margin.push({text:"2",value:"2"});

//font padding
$dropDataPlugin.drop.padding = [];
$dropDataPlugin.drop.padding.push({text:"0",value:"0"});
$dropDataPlugin.drop.padding.push({text:"1",value:"1"});
$dropDataPlugin.drop.padding.push({text:"2",value:"2"});

//fontSize drops
$dropDataPlugin.drop.fontSize = [];
$dropDataPlugin.drop.fontSize.push({text:".4",value:".4"});
$dropDataPlugin.drop.fontSize.push({text:".5",value:".5"});
$dropDataPlugin.drop.fontSize.push({text:".6",value:".6"});
$dropDataPlugin.drop.fontSize.push({text:".7",value:".7"});
$dropDataPlugin.drop.fontSize.push({text:".8",value:".8"});
$dropDataPlugin.drop.fontSize.push({text:".9",value:".9"});
$dropDataPlugin.drop.fontSize.push({text:"1",value:"1"});
$dropDataPlugin.drop.fontSize.push({text:"2",value:"2"});
$dropDataPlugin.drop.fontSize.push({text:"3",value:"3"});
$dropDataPlugin.drop.fontSize.push({text:"4",value:"4"});
$dropDataPlugin.drop.fontSize.push({text:"5",value:"5"});
$dropDataPlugin.drop.fontSize.push({text:"6",value:"6"});
$dropDataPlugin.drop.fontSize.push({text:"7",value:"7"});
$dropDataPlugin.drop.fontSize.push({text:"8",value:"8"});
$dropDataPlugin.drop.fontSize.push({text:"9",value:"9"});
$dropDataPlugin.drop.fontSize.push({text:"10;",value:"10;"});
$dropDataPlugin.drop.fontSize.push({text:"11",value:"11"});
$dropDataPlugin.drop.fontSize.push({text:"12",value:"12"});
$dropDataPlugin.drop.fontSize.push({text:"13",value:"13"});
$dropDataPlugin.drop.fontSize.push({text:"14",value:"14"});
$dropDataPlugin.drop.fontSize.push({text:"15",value:"15"});
$dropDataPlugin.drop.fontSize.push({text:"16",value:"16"});
$dropDataPlugin.drop.fontSize.push({text:"17",value:"17"});
$dropDataPlugin.drop.fontSize.push({text:"18",value:"18"});
$dropDataPlugin.drop.fontSize.push({text:"19",value:"19"});
$dropDataPlugin.drop.fontSize.push({text:"20",value:"20"});
$dropDataPlugin.drop.fontSize.push({text:"21",value:"21"});
$dropDataPlugin.drop.fontSize.push({text:"22",value:"22"});
$dropDataPlugin.drop.fontSize.push({text:"23",value:"23"});
$dropDataPlugin.drop.fontSize.push({text:"24",value:"24"});
$dropDataPlugin.drop.fontSize.push({text:"25",value:"25"});
$dropDataPlugin.drop.fontSize.push({text:"26",value:"26"});
$dropDataPlugin.drop.fontSize.push({text:"27",value:"27"});
$dropDataPlugin.drop.fontSize.push({text:"28",value:"28"});
$dropDataPlugin.drop.fontSize.push({text:"29",value:"29"});
$dropDataPlugin.drop.fontSize.push({text:"30",value:"30"});
$dropDataPlugin.drop.fontSize.push({text:"31",value:"31"});
$dropDataPlugin.drop.fontSize.push({text:"32",value:"32"});
$dropDataPlugin.drop.fontSize.push({text:"33",value:"33"});
$dropDataPlugin.drop.fontSize.push({text:"34",value:"34"});
$dropDataPlugin.drop.fontSize.push({text:"35",value:"35"});
$dropDataPlugin.drop.fontSize.push({text:"36",value:"36"});
$dropDataPlugin.drop.fontSize.push({text:"37",value:"37"});
$dropDataPlugin.drop.fontSize.push({text:"38",value:"38"});
$dropDataPlugin.drop.fontSize.push({text:"39",value:"39"});
$dropDataPlugin.drop.fontSize.push({text:"40",value:"40"});
$dropDataPlugin.drop.fontSize.push({text:"41",value:"41"});
$dropDataPlugin.drop.fontSize.push({text:"42",value:"42"});
$dropDataPlugin.drop.fontSize.push({text:"43",value:"43"});
$dropDataPlugin.drop.fontSize.push({text:"44",value:"44"});
$dropDataPlugin.drop.fontSize.push({text:"45",value:"45"});
$dropDataPlugin.drop.fontSize.push({text:"46",value:"46"});
$dropDataPlugin.drop.fontSize.push({text:"47",value:"47"});
$dropDataPlugin.drop.fontSize.push({text:"48",value:"48"});
$dropDataPlugin.drop.fontSize.push({text:"49",value:"49"});

$dropDataPlugin.drop.border = [];
$dropDataPlugin.drop.border.push({text:"0",value:"0"});
$dropDataPlugin.drop.border.push({text:".5",value:".5"});
$dropDataPlugin.drop.border.push({text:"1",value:"1"});
$dropDataPlugin.drop.border.push({text:"2",value:"2"});
$dropDataPlugin.drop.border.push({text:"3",value:"3"});
$dropDataPlugin.drop.border.push({text:"4",value:"4"});
$dropDataPlugin.drop.border.push({text:"5",value:"5"});
$dropDataPlugin.drop.border.push({text:"6",value:"6"});
$dropDataPlugin.drop.border.push({text:"7",value:"7"});
$dropDataPlugin.drop.border.push({text:"8",value:"8"});
$dropDataPlugin.drop.border.push({text:"9",value:"9"});
$dropDataPlugin.drop.border.push({text:"10",value:"10"});

window.$dropDataPlugin = $dropDataPlugin
	return (this);
}
());
